steps:
  - name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        echo "REACT_APP_API_GATEWAY_URL=${_REACT_APP_API_GATEWAY_URL}" > .env
        echo "REACT_APP_API_MOBILE_URL=${_REACT_APP_API_MOBILE_URL}" > .env
        npm run build

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gsutil -m rsync -r -d build gs://${_GCS_BUCKET}

substitutions:
  _GCS_BUCKET: brevio-media-dev-public
  _REACT_APP_API_GATEWAY_URL: https://bsstaging.brainvire.dev/cms/  # You can override this per trigger
  _REACT_APP_API_MOBILE_URL: https://bsstaging.brainvire.dev/backend/
timeout: 6000s
