steps:
  - name: 'gcr.io/${_PROJECT_ID}/terraform'  # Make sure this image exists in GCR or use an official Terraform image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd environments/${_ENVIRONMENT}
        # terraform init
        # terraform destroy -auto-approve
        terraform init
        terraform apply -auto-approve
    dir: terraform



  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y jq
        echo "Fetching all secrets with prefix '${_SECRET_NAME}'..."
        secret_value=$(gcloud secrets versions access latest --secret="${_SECRET_NAME}" --format="json")
        decoded_secret=$(echo "$secret_value" | jq -r '.payload.data' | base64 --decode)

        echo "REACT_APP_API_GATEWAY_URL=$(echo "$decoded_secret" | jq -r '.REACT_APP_API_GATEWAY_URL')" >> .env
        echo "REACT_APP_API_MOBILE_URL=$(echo "$decoded_secret" | jq -r '.REACT_APP_API_MOBILE_URL')" >> .env
        echo "REACT_APP_ENCRYPTION_DECRYPTION_KEY=$(echo "$decoded_secret" | jq -r '.REACT_APP_ENCRYPTION_DECRYPTION_KEY')" >> .env
        echo "REACT_APP_API_BASENODE=$(echo "$decoded_secret" | jq -r '.REACT_APP_API_BASENODE')" >> .env
        echo "REACT_APP_GOOGLE_MAPS_API_KEY=$(echo "$decoded_secret" | jq -r '.REACT_APP_GOOGLE_MAPS_API_KEY')" >> .env
        echo "REACT_APP_STRIPE_PUBLIC_KEY=$(echo "$decoded_secret" | jq -r '.REACT_APP_STRIPE_PUBLIC_KEY')" >> .env

        echo "All secrets have been stored in .env file."

    env:
      - "SECRET_NAME=${_SECRET_NAME}"     

#Create the production build
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - "-c"
      - |
        export $(grep -v '^#' .env | xargs)
        npm install
        npm run build


  # 4. Deploy to Google Cloud Storage
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil rsync -R build gs://${_PROJECT_ID}-${_ENVIRONMENT}-cms-ui
        gsutil web set -m index.html -e index.html gs://${_PROJECT_ID}-${_ENVIRONMENT}-cms-ui
        gsutil iam ch allUsers:objectViewer gs://${_PROJECT_ID}-${_ENVIRONMENT}-cms-ui


timeout: 6000s
options:
  logging: CLOUD_LOGGING_ONLY