export const PERMISSION_LIST = {
	Dashboard: {
		DashboardAccess: '',
	},
	SubAdmin: {
		ListAccess: 'LIST_SUB_ADMIN',
		AddAccess: 'CREATE_SUB_ADMIN',
		EditAccess: 'UPDATE_ADMIN_EDIT',
		ChangeStatusAccess: 'SUB_ADMIN_CHANGE_STATUS',
		DeleteAccess: 'DELETE_SUB_ADMIN',
		GroupDeleteAcsess: 'GROUP_DELETE_SUB_ADMIN',
		ChangePasswordAccess: 'CHANGE_PASSWORD_SUB_ADMIN',
	},
	UserManagement: {
		ListAccess: 'LIST_USERS',
		AddAccess: '',
		EditAccess: 'USER_UPDATE',
		ViewAccess: 'VIEW_USER',
		ChangeStatusAccess: 'USER_UPDATE_STATUS',
		DeleteAccess: 'DELETE_USER',
		GroupDeleteAcsess: 'GROUP_DELETE_USERS',
		ChangePasswordAccess: 'CHANGE_USER_PASSWORD',
	},
	FAQ: {
		ListAccess: 'FAQ_LIST_TOPIC',
		AddAccess: 'FAQ_CREATE_TOPIC',
		EditAccess: 'FAQ_UPDATE_TOPIC',
		ChangeStatusAccess: 'FAQ_QA_CHANGE_STATUS',
		DeleteAccess: 'FAQ_DELETE_TOPIC',
		GroupDeleteAcsess: 'GROUP_DELETE_FAQ_TOPIC',
	},
	CMS: {
		ListAccess: 'FETCH_CMS',
		AddAccess: 'CREATE_CMS',
		EditAccess: 'UPDATE_CMS',
		ChangeStatusAccess: 'UPDATE_CMS_STATUS',
		DeleteAccess: 'DELETE_CMS',
		GroupDeleteAcsess: 'GROUP_DELETE_CMS',
	},
	Enquiry: {
		ListAccess: 'FETCH_ENQUIRY',
		AddAccess: 'CREATE_ENQUIRY',
		ChangeStatusAccess: 'UPDATE_STATUS',
		DeleteAccess: 'DELETE_ENQUIRY',
		GroupDeleteAcsess: 'GROUP_DELETE_ENQUIRY',
	},
	EmailTemplate: {
		ListAccess: 'EMAIL_TEMPLATE_LIST',
		AddAccess: 'EMAIL_TEMPLATE_CREATE',
		EditAccess: 'EMAIL_TEMPLATE_UPDATE',
		ChangeStatusAccess: 'EMAIL_STATUS_UPDATE',
		DeleteAccess: 'EMAIL_TEMPLATE_DELETE',
		GroupDeleteAcsess: 'GROUP_EMAIL_TEMPLATE_DELETE',
	},
	Announcement: {
		ListAccess: 'FETCH_ANNOUNCEMENT_WITH_FILTERS',
		AddAccess: 'CREATE_ANNOUNCEMENT',
		ViewAccess: 'FETCH_SINGLE_ANNOUNCEMENT',
	},
	Role: {
		ListAccess: 'LIST_ROLE',
		AddAccess: 'CREATE_ROLE',
		EditAccess: 'UPDATE_ROLE',
		ChangeStatusAccess: 'ROLE_CHANGE_STATUS',
		DeleteAccess: 'DELETE_ROLE',
	},
	Permission: {
		ListAccess: 'LIST_PERMISSIONS',
		FetchRolePermissions: 'FETCH_ROLE_PERMISSIONS',
		createAccess: 'UPDATE_ROLE_PERMISSIONS',
	},
	Settings: {
		ListAccess: 'SETTING_LIST',
		EditAccess: 'UPDATE_AND_CREATE_SETTING',
	},
	BsMedia: {
		ListAccess: 'FETCH_LIST_OF_BS_MEDIA',
		AddFolderAccess: 'FOLDER_CREATE_BS_MEDIA',
		RenameAccess: 'RENAME_BS_MEDIA',
		DeleteAccess: 'GROUP_DELETE_BS_MEDIA',
		MoveAccess: 'MOVE_BS_MEDIA',
		ViewAccess: 'GET_BS_MEDIA_DETAIL',
	},
	Banner: {
		ListAccess: 'FETCH_BANNER',
		EditAccess: 'UPDATE_BANNER',
		AddAccess: 'CREATE_BANNER',
		ChangeStatusAccess: 'UPDATE_BANNER_STATUS',
		DeleteAccess: 'DELETE_SINGLE_BANNER',
		GroupDeleteAcsess: 'DELETE_GROUP_BANNER',
	},

	Country: {
		ListAccess: 'FETCH_COUNTRIES_WITH_PAGINATION',
		EditAccess: 'UPDATE_COUNTRY',
		AddAccess: 'CREATE_COUNTRY',
		ChangeStatusAccess: 'CHANGE_COUNTRY_STATUS',
		DeleteAccess: 'DELETE_COUNTRY',
		GroupDeleteAcsess: 'GROUP_DELETE_COUNTRY',
	},

	State: {
		ListAccess: 'FETCH_STATES',
		EditAccess: 'UPDATE_STATE',
		AddAccess: 'CREATE_STATE',
		ChangeStatusAccess: 'CHANGE_STATE_STATUS',
		DeleteAccess: 'DELETE_STATE',
		GroupDeleteAcsess: 'GROUP_DELETE_STATES',
	},
	Coupon: {
		ListAccess: 'FETCH_OFFERS',
		EditAccess: 'UPDATE_OFFER',
		AddAccess: 'CREATE_OFFER',
		ChangeStatusAccess: 'UPDATE_OFFER_STATUS',
		DeleteAccess: 'DELETE_OFFER',
		GroupDeleteAcsess: 'GROUP_DELETE_OFFER',
	},
	City: {
		ListAccess: 'FETCH_CITIES',
		EditAccess: 'UPDATE_CITY',
		AddAccess: 'CREATE_CITY',
		ChangeStatusAccess: 'CHANGE_CITY_STATUS',
		DeleteAccess: 'DELETE_CITY',
		GroupDeleteAcsess: 'GROUP_DELETE_CITIES',
	},
	UserReport: {
		ListAccess: 'USER_REPORTS',
		ChangeStatusAccess: 'USER_REPORT_CHANGE_STATUS',
		DeleteAccess: 'DELETE_USER_REPORT',
		GroupDeleteAcsess: 'GROUP_DELETE_USER_REPORT',
	},
	Suggestion: {
		ListAccess: 'SUGGESTION_LIST',
		ChangeStatusAccess: 'UPDATE_SUGGESTION_STATUS',
		EditAccess: 'UPDATE_SUGGESTION',
		AddAccess: 'CREATE_SUGGESTION',
		DeleteAccess: 'DELETE_SUGGESTION',
		GroupDeleteAcsess: 'GROUP_DELETE_SUGGESTION',
	},
	Review: {
		ListAccess: 'FETCH_REVIEWS',
		AddAccess: 'CREATE_REVIEW',
		ChangeStatusAccess: 'UPDATE_STATUS_REVIEW',
		DeleteAccess: 'DELETE_REVIEW',
		GroupDeleteAcsess: 'GROUP_DELETE_REVIEW',
	},
	ActivityTracking: {
		ListAccess: 'FETCH_ACTIVITIES',
		AddAccess: 'CREATE_ACTIVITY',
		DeleteAccess: 'DELETE_ACTIVITY',
		GroupDeleteAcsess: 'GROUP_DELETE_ACITIVITY',
	},
	QrCode: {
		ListAccess: 'FETCH_QRCODE',
		AddAccess: 'CREATE_QRCODE',
		EditAccess: 'UPDATE_QRCODE',
		ChangeStatusAccess: 'UPDATE_STATUS_QRCODE',
		DeleteAccess: 'DELETE_QRCODE',
		GroupDeleteAcsess: 'GROUP_DELETE_QRCODE',
	},
	GeoLocation: {
		ListAccess: 'FETCH_GEO_LOCATION',
		AddAccess: 'CREATE_GEO_LOCATION',
		EditAccess: 'UPDATE_GEO_LOCATION',
		ChangeStatusAccess: 'UPDATE_STATUS_GEO_LOCATION',
		DeleteAccess: 'DELETE_GEO_LOCATION',
		GroupDeleteAcsess: 'GROUP_DELETE_GEO_LOCATION',
		ViewAccess: 'VIEW_ACCESS_GEOLOCATION',
	},
	PlanManagement: {
		ListAccess: 'FETCH_PLAN_MANAGEMENT',
		AddAccess: 'CREATE_PLAN_MANAGEMENT',
		EditAccess: 'UPDATE_PLAN_MANAGEMENT',
		ChangeStatusAccess: 'UPDATE_STATUS_PLAN_MANAGEMENT',
		DeleteAccess: 'DELETE_PLAN_MANAGEMENT',
		GroupDeleteAcsess: 'GROUP_DELETE_PLAN_MANAGEMENT',
	},
	Book: {
		ListAccess: 'LIST_BOOK',
		AddAccess: 'CREATE_BOOK',
		EditAccess: 'UPDATE_BOOK',
		ChangeStatusAccess: 'BOOK_CHANGE_STATUS',
		DeleteAccess: 'DELETE_BOOK',
		publishAccess: 'PUBLISH_BOOK',
		refineBook: 'REFINE_BOOK_DATA',
		generateBook: 'GENERATE_BOOK_DATA'
	},
	Category: {
		ListAccess: 'LIST_CATEGORY',
		AddAccess: 'CREATE_CATEGORY',
		EditAccess: 'UPDATE_CATEGORY',
		ChangeStatusAccess: 'CATEGORY_CHANGE_STATUS',
		DeleteAccess: 'DELETE_CATEGORY',
	},
	Author: {
		ListAccess: 'LIST_AUTHOR',
		AddAccess: 'CREATE_AUTHOR',
		EditAccess: 'UPDATE_AUTHOR',
		ChangeStatusAccess: 'AUTHOR_CHANGE_STATUS',
		DeleteAccess: 'DELETE_AUTHOR',
	}
};

export const COMMAND_LIST: { [key: string]: string } = {
	'ROLE': 'src/types/role.d.ts src/framework/graphql/mutations/role.ts src/framework/graphql/queries/role.ts src/views/role',
	'SUGGESTION': 'src/views/suggestion src/types/suggestion.d.ts src/framework/graphql/mutations/suggestion.ts src/framework/graphql/queries/suggestion.ts',
	'USER': 'src/views/userManagement src/types/user.d.ts src/framework/graphql/queries/user.ts src/framework/graphql/mutations/user.ts',
	'REVIEW': 'src/views/review src/types/review.d.ts src/framework/graphql/queries/review.ts src/framework/graphql/mutations/review.ts',
	'ANNOUNCEMENT': 'src/views/viewAnnouncement src/views/announcement src/types/announcement.d.ts src/framework/graphql/queries/announcement.ts src/framework/graphql/mutations/announcement.ts',
	'ACTIVITY-TRACKING': 'src/framework/graphql/mutations/activitytracking.ts src/framework/graphql/queries/activityTracking.ts src/types/activityTracking.d.ts src/views/activityTracking',
	'CITY': 'src/views/city src/types/city.d.ts src/framework/graphql/queries/city.ts src/framework/graphql/mutations/city.ts',
	'PERMISSIONS': 'src/views/rolePermissons src/types/rolePermissions.d.ts src/framework/graphql/mutations/rolePermission.ts src/framework/graphql/queries/rolePermissions.ts',
	'STATE': 'src/framework/graphql/mutations/state.ts src/framework/graphql/queries/state.ts src/types/state.ts src/views/state',
	'USER REPORT': 'src/views/userReport src/types/userReport.ts src/framework/graphql/queries/userReport.ts src/framework/graphql/mutations/userReport.ts',
	'BS MEDIA': 'src/framework/graphql/mutations/bsMedia.ts src/framework/graphql/queries/bsMedia.ts src/types/bsMedia.d.ts src/views/bs-media',
	'OFFER': 'src/views/couponsManagement src/types/couponManagement.d.ts src/framework/graphql/queries/couponManagement.ts src/framework/graphql/mutations/couponManagement.ts',
	'PLAN MANAGEMENT': 'src/views/planManagement src/types/planManagement.d.ts src/framework/graphql/queries/planManagement.ts src/framework/graphql/mutations/planManagement.ts',
	'SUB ADMIN': 'src/framework/graphql/mutations/subAdmin.ts src/framework/graphql/queries/subAdmin.ts src/views/subAdmin src/types/subAdmin.d.ts',
	'EMAIL TEMPLATE': 'src/views/emailNotificationTemplate src/types/emailNotificationTemplate.d.ts src/framework/graphql/queries/emailNotificationTemplate.ts src/framework/graphql/mutations/emailNotificationTemplate.ts',
	'SETTINGS': 'src/framework/graphql/mutations/settings.ts src/types/settings.d.ts src/views/settingsPage',
	'COUNTRY': 'src/framework/graphql/mutations/country.ts src/framework/graphql/queries/country.ts src/views/country src/types/country.ts',
	'ENQUIRY': 'src/framework/graphql/mutations/enquiry.ts src/framework/graphql/queries/enquiry.ts src/views/enquiry src/types/enquiry.d.ts',
	'FAQ Management': 'src/views/faq src/types/faq.d.ts src/framework/graphql/queries/faq.ts src/framework/graphql/mutations/faq.ts',
	'BANNER': 'src/framework/graphql/mutations/banner.ts src/framework/graphql/queries/banner.ts src/types/banner.d.ts src/views/banner',
	'CMS': 'src/types/cms.d.ts src/views/CMS src/framework/graphql/queries/cms.ts src/framework/graphql/mutations/cms.ts',
	'USER SETTING': '',
	'QRCODE': 'src/views/qrCode src/types/qrcode.d.ts src/framework/graphql/queries/qrCode.ts src/framework/graphql/mutations/qrCode.ts',
	'Geo Location': 'src/views/geoLocation src/types/geoLocation.d.ts src/framework/graphql/mutations/geoLocation.ts src/framework/graphql/queries/geoLocation.ts src/types/geoLocation.d.ts',
	'Category': 'src/views/manageCategory src/types/category.d.ts src/framework/graphql/queries/category.ts src/framework/graphql/mutations/category.ts',
	'Event Management': 'src/views/eventsManagement src/views/viewEvent src/types/event.d.ts src/framework/graphql/queries/event.ts src/framework/graphql/mutations/event.ts',
	'Rule sets Management': 'src/views/rulesSestsManagement src/types/manageRulesSets.d.ts src/framework/graphql/queries/manageRulesSets.ts src/framework/graphql/mutations/manageRulesSets.ts',
	'Notification': 'src/views/viewNotification src/views/notifications src/types/notifications.d.ts src/framework/graphql/queries/notifications.ts src/framework/graphql/mutations/notifications.ts',
	'Subscription Management': 'src/views/subscriptionManagement src/types/subscription.d.ts src/types/payment.d.ts src/framework/graphql/queries/subscription.ts src/hooks/useStripePaymentInitilization.tsx'
}

